version: 2

before:
  hooks:
    - go mod download

builds:
  - id: nebu-sql
    main: ./cmd/nebu-sql
    binary: nebu-sql
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/withObsrvr/nebu-sql/internal/version.Value={{.Version}}

archives:
  - id: nebu-sql
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
